### ISSUE TITLE
OSX install fails

### ISSUE THREAD

**Issue by jjv5** [tlambert03/pycudadecon#10]
OSX 10.14 install using conda (py3) fails due to conflicts, but with no message about the conflicts:

Solving environment: / 

Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed                                                                                                                             

UnsatisfiableError: The following specifications were found to be incompatible with each other:

Output in format: Requested package -> Available versions

 $ ./conda -V
conda 4.8.3
 $ ./python --version
Python 3.7.4
"

**Comment by tlambert03** [comment]
Thanks @jjv5 , I’m aware that the Mac conda install is broken at the moment... I kinda assumed that I was the only one actually using it :)

However, I have a Mac with an NVIDIA card that I’m holding at 10.13 since Mac dropped support for CUDA I’m 10.14.  Do you have appropriate hardware and reason to suspect that cuda will work for you ion 10.14?

**Comment by tlambert03** [comment]
let me know if you have reason to hope this could work for you on 10.14, otherwise I'll probably close this issue.  Thanks
