### ISSUE TITLE
Handle large OTFs better [RLgpuImpl.cu(86) : cudaSafeCall() : invalid argument]

### ISSUE THREAD

**Issue by pmcarlton** [tlambert03/pycudadecon#3]
Hello, thanks for making this!
I installed this through miniconda on Ubuntu 16.04, and received an error.
The image and PSF are both 16-bit TIFF files.

Here's the ipython interactive session:
```
>> ipython
Python 3.7.1 | packaged by conda-forge | (default, Feb 26 2019, 04:48:14) 
Type 'copyright', 'credits' or 'license' for more information
IPython 7.3.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: psff='psfG100.1512.tif'                                                                                                                                                                                     

In [2]: imf='c016_G_n2_s4g0_3.tif'                                                                                                                                                                                  

In [3]: from pycudadecon import decon                                                                                                                                                                               

In [4]: result=decon(imf,psff)                                                                                                                                                                                      
callednx=480, ny=480, nz=40
Center of mass is (237.714, 241.797, 20.563)
Background is 99.289
In radialft()
output nz=90
/home/talley/Documents/cudaDeconvOriginal/RLgpuImpl.cu(86) : cudaSafeCall() Runtime API error 1: invalid argument.
```

Here is GPU info:

```
(decon) (255)[13:24][pcarlton@chromosome-linux:~]
>> nvidia-smi
Fri Mar  8 13:26:22 2019       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 418.39       Driver Version: 418.39       CUDA Version: 10.1     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX 980     Off  | 00000000:01:00.0 Off |                  N/A |
| 27%   43C    P0    33W / 180W |      0MiB /  4035MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+

```

**Comment by pmcarlton** [comment]
[Link to PSF file](https://www.dropbox.com/s/0h3ku5mf9uisplf/psfG100.1512.tif)
[Link to Image file](https://www.dropbox.com/s/k02vt2rtitfrul5/c016_G_n2_s4g0_3.tif)

**Comment by tlambert03** [comment]
Hi Peter, and thanks for giving it a shot!
This is an issue that I need to fix (or at least handle better) with the size of the PSF file.  I was able to repeat your issue, but if I cropped the PSF to anything smaller than 40 x 380 x 380, it worked for me (at 40 x 384 x 384 it crashed).  I'm not entirely sure why that is yet... my GPU should have plenty of memory for it.  Also, I noticed that if you convert the PSF into an OTF file manually first (using `pycudadecon.make_otf(psfpath)` and then hand that OTF file to the decon function, it works fine even at full size. So it's certainly something related to memory, but I need to be able to predict it a little better, and provide meaningful error messages, and possibly some auto-cropping.  I'm worried that you'll also run into issues with 4GB GPU memory and the size of your image file... but can you try cropping your PSF to around 128x128 and try again?

**Comment by tlambert03** [comment]
@linshaova, maybe you can help shed some light on this one?

I've seen this phenomenon before, where a large PSF file will seemingly generate an OTF just fine using radialft, but then throw "invalid argument" when transferring constants to the GPU during deconvolution at the line `  cutilSafeCall(cudaMemcpyToSymbol(const_otf, h_otf, nrotf*nzotf*2*sizeof(float)));` in RLgpuImpl.cu.

However, I haven't been able to pin down exact what defines "large" here or why it's choking.
I feel like it's related to fix_origin somehow... for instance, on Peter's full size PSF linked above, the origin is _not_ 1.0 regardless of what I use for fixorigin. Rather, the third pixel down is 1.0, and the origin is slightly below that.  If I crop the file a bit, to around 40 x 390 x 390, then the origin is back to 1.0, but decon still chokes when transferring unless I crop even further.  In the past, I've seen a similar effect with small XY but large Z dimensions of the OTF.

It doesn't feel like a memory issue (i.e, the image, FFT plan and OTF don't seem to be fighting for space): I can crop the image volume down to a rather small volume and I still get the error.  It's only when I bring the PSF size down that it works.

would be nice to hone in either on a way to fix this, or on a rational method to predict when it's going to fail...

**Comment by linshaova** [comment]
Most Nvidia cards have about 64k bytes constant memory. 40x390x390 converted to OTF is 196x40x8 bytes, which is 62720 bytes. And maybe there are also other constants transferred to the constant memory? I forgot. But it’s tight.
We should change it to use RAM on device so that we won’t be limited by the constant memory. I don’t remember why I decided to use constant memory for OTF.


lin

On Friday, March 8, 2019, 23:53, Talley Lambert <notifications@github.com> wrote:


@linshaova, maybe you can help shed some light on this one?

I've seen this phenomenon before, where a large PSF file will seemingly generate an OTF just fine using radialft, but then throw "invalid argument" when transferring constants to the GPU during deconvolution at the line  cutilSafeCall(cudaMemcpyToSymbol(const_otf, h_otf, nrotf*nzotf*2*sizeof(float))); in RLgpuImpl.cu.

However, I haven't been able to pin down exact what defines "large" here or why it's choking.
I feel like it's related to fix_origin somehow... for instance, on Peter's full size PSF linked above, the origin is not 1.0 regardless of what I use for fixorigin. Rather, the third pixel down is 1.0, and the origin is slightly below that. If I crop the file a bit, to around 40 x 390 x 390, then the origin is back to 1.0, but decon still chokes when transferring unless I crop even further. In the past, I've seen a similar effect with small XY but large Z dimensions of the OTF.

It doesn't feel like a memory issue (i.e, the image, FFT plan and OTF don't seem to be fighting for space): I can crop the image volume down to a rather small volume and I still get the error. It's only when I bring the PSF size down that it works.

would be nice to hone in either on a way to fix this, or on a rational method to predict when it's going to fail...

**Comment by tlambert03** [comment]
ahh, that's right.  That answers it.  After reading up on it a bit, it sounds like constant memory was indeed an appropriate choice, provided it's not too small... but maybe we should look again at texture memory (before putting it somewhere global), since it should be large enough and is particularly well suited to the types of interpolation that needs to be done with the OTF?  I see that you played with this a while back but it looks like maybe it didn't work and got abandoned... thoughts there?

on the python side, in the meantime, I can put in some size checking, and auto-crop (with a warning, or a `allow_crop` parameter or something).  I suspect the impact of cropping will be negligible in many cases... except perhaps for highly oversampled PSFs?

**Comment by tlambert03** [comment]
Hi @pmcarlton, I updated pycudadecon to detect whether the generated OTF is going to be larger than 60K, and crop the PSF accordingly prior to deconvolution.  If you'd like to try it, update to pycudadecon 0.1.1 (use `conda update pycudadecon` in your conda environment). `pycudadecon.decon(image, psf)` should now work with your example PSF and image file (provided there's enough RAM on your GTX 980 for the image file...).  But let me know if you run into issues.

**Comment by pmcarlton** [comment]
Hey, I just tried it and it works perfectly! Thanks a lot for the quick fix. 
Output log follows:
```
callednx=372, ny=372, nz=40
Center of mass is (185.714, 185.797, 20.563)
Background is 99.256
In radialft()
output nz=90
X_k allocated.               360MB    2436MB free Pinning Host RAM.  Copy raw.data to X_k HostToDevice.  Done.  
rawGPUbuf allocated.         360MB    2076MB free
X_kminus1 allocated.         360MB    1716MB free
Y_k allocated.               360MB    1356MB free
CC allocated.                360MB     996MB free
G_kminus1 allocated.         360MB     636MB free
G_kminus2 allocated.         360MB     276MB free
Want new 360 MB of GPU RAM. 274 MB free / 4035 MB total. Use Host RAM...
fftGPUbuf allocated.         360MB     274MB free
Iteration 0. 
Iteration 1. 
Iteration 2. Lambda = 0.67. 
Iteration 3. Lambda = 0.64. 
Iteration 4. Lambda = 0.69. 
Iteration 5. Lambda = 0.76. 
Iteration 6. Lambda = 0.82. 
Iteration 7. Lambda = 0.85. 
Iteration 8. Lambda = 0.86. 
Iteration 9. Lambda = 0.87. 
```

**Comment by linshaova** [comment]
Sorry for the late reply. Has been traveling since Saturday (in Japan with Pete Carlton!).
Yes texture memory at one point was on my to do list. but for some reason that I don't remember now, I did not pursue it. Most likely due to lack of motivation to work around some barrier. I don't think there should be anything insurmountable though. So feel free to explore and let me know if you need my help. Thanks!
lin
    On Monday, March 11, 2019, 2:03:38 AM GMT+9, Talley Lambert <notifications@github.com> wrote:  
 
 
ahh, that's right. That answers it. After reading up on it a bit, it sounds like constant memory was indeed an appropriate choice, provided it's not too small... but maybe we should look again at texture memory (before putting it somewhere global), since it should be large enough and is particularly well suited to the types of interpolation that needs to be done with the OTF? I see that you played with this a while back but it looks like maybe it didn't work and got abandoned... thoughts there?

on the python side, in the meantime, I can put in some size checking, and auto-crop (with a warning, or a allow_crop parameter or something). I suspect the impact of cropping will be negligible in many cases... except perhaps for highly oversampled PSFs?
